[package]
name = "stein-broker-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Security_Cryptography",
    "Win32_Security_Isolation",
    "Win32_Storage_Packaging_Appx",
    "Win32_System_Pipes",
    "Win32_System_Threading",
] }
